name: 'Terraform Extarct Secret'

on:
  workflow_dispatch:
    
jobs:
  extract-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Secret
        run: echo "My secret value is ${{ secrets.AZURE_CREDENTIALS }}"
      

    
